DROP TABLE IF EXISTS ENVIRONMENT;
DROP TABLE IF EXISTS PROPERTIES;
DROP SEQUENCE IF EXISTS PROPERTIES_ID_SEQ;
DROP SEQUENCE IF EXISTS ENVIRONMENT_ID_SEQ;
DROP SCHEMA IF EXISTS CONFIG;

CREATE SCHEMA CONFIG;
SET SCHEMA CONFIG;

CREATE SEQUENCE APP_ENVIRONMENT_ID_SEQ START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE APP_PROPERTIES_ID_SEQ START WITH 0 INCREMENT BY 1;

CREATE TABLE APP_ENVIRONMENT (
  APP_ENVIRONMENT_ID BIGINT DEFAULT APP_ENVIRONMENT_ID_SEQ.nextval NOT NULL,
  APP_ENVIRONMENT_NAME VARCHAR(255) NOT NULL,
  APP_ENVIRONMENT_DESCRIPTION VARCHAR(255),
  CREATED_BY_USER VARCHAR(255) DEFAULT 'SYSTEM' NOT NULL,
  CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
  LAST_MODIFICATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(255) DEFAULT 'SYSTEM' NOT NULL,
  VERSION BIGINT NOT NULL,

  PRIMARY KEY (APP_ENVIRONMENT_ID)
);


CREATE TABLE APP_PROPERTIES (
  APP_PROPERTIES_ID BIGINT DEFAULT APP_PROPERTIES_ID_SEQ.nextval NOT NULL,
  APP_PROPERTY_KEY VARCHAR(512) NOT NULL ,
  APP_PROPERTY_VALUE CLOB NOT NULL,
  APP_ENVIRONMENT_ID BIGINT NOT NULL REFERENCES APP_ENVIRONMENT(APP_ENVIRONMENT_ID),
  CREATED_BY_USER VARCHAR(255) DEFAULT 'SYSTEM' NOT NULL,
  CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_MODIFICATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(255) DEFAULT 'SYSTEM' NOT NULL,
  VERSION BIGINT NOT NULL,

  PRIMARY KEY (APP_PROPERTIES_ID)
);



