-- INSERTS FOR APP ENVIRONMENTS
INSERT INTO APP_ENVIRONMENT(APP_ENVIRONMENT_NAME, APP_ENVIRONMENT_DESCRIPTION, VERSION) VALUES ('COMMON','COMMON ENVIRONMENT',0 );
INSERT INTO APP_ENVIRONMENT(APP_ENVIRONMENT_NAME, APP_ENVIRONMENT_DESCRIPTION, VERSION) VALUES ('DEV','DEVELOPMENT ENVIRONMENT',1 );
INSERT INTO APP_ENVIRONMENT(APP_ENVIRONMENT_NAME, APP_ENVIRONMENT_DESCRIPTION, VERSION) VALUES ('QA','QUALITY ASSURANCE ENVIRONMENT',2 );
INSERT INTO APP_ENVIRONMENT(APP_ENVIRONMENT_NAME, APP_ENVIRONMENT_DESCRIPTION, VERSION) VALUES ('PROD','PRODUCTION ENVIRONMENT',3 );


--INSERTS FOR APP PROPERTIES
-- COMMON PROPERTIES


--HIBERNATE SETTINGS
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.dialect','org.hibernate.dialect.H2Dialect',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.hbm2ddl.auto','validate',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.ejb.naming_strategy','org.hibernate.cfg.ImprovedNamingStrategy',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.format_sql','true',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.show_sql','true',0,0);

--HIBERNATE CACHING SETTINGS
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.cache.use_second_level_cache','true',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.cache.use_query_cache','true',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('hibernate.cache.region.factory_class','org.hibernate.cache.ehcache.EhCacheRegionFactory',0,0);


-- NYTIMES KEYS
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.ARTICLE_SEARCH_API.KEY','d4d1d127258358ea360e2551047c40fa:3:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.BOOKS_API.KEY','679195bfc50dfcd0a9c15acd4fb4962c:11:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.CAMPAIGN_FINANCE_API.KEY','3524f4fe34a7c7e222f8e5ddd76a0679:17:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.COMMUNITY_API.KEY','4738bd91cefb4eaa40e6dfb73f7c1e0d:9:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.CONGRESS_API.KEY','fe651112ed313751be74e77ee5b7568d:17:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.DISTRICTS_API.KEY','bc48e3fe2b3b8acb414c35a275294f1b:7:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.EVENT_LISTING_API.KEY','35b6adadf0c7dad08d3a0533a8de1946:1:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.GEO_API.KEY','4d80f18722d00f0968b71e8ef9a88f0e:9:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.MOST_POPULAR_API.KEY','e4293bdf5b91e2035601988ebb3ea1b6:16:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.MOVIE_REVIEWS_API.KEY','004dac5044490f20365a9d75a9f1e254:3:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.SEMANTIC_API.KEY','47d82f6f67a37585be58053cf705f0e4:11:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.TIMES_TAGS_API.KEY','042c60de26d0c86acbd89c9f944a3f2e:13:49442228',0,0);
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.TOP_STORIES_API.KEY','d3092d92e8c0b3305db5e2b09682b7fe:6:49442228',0,0);


-- DEV PORPERTIES
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.TOP_STORIES_API.KEY','DEV',1,0);

--QA PROPERTIES
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.TOP_STORIES_API.KEY','QA',2,0);

--PROD PROPERITES
INSERT INTO APP_PROPERTIES(APP_PROPERTY_KEY, APP_PROPERTY_VALUE,APP_ENVIRONMENT_ID, VERSION)
VALUES ('NYTIMES.TOP_STORIES_API.KEY','PROD',3,0);


