DROP TABLE IF EXISTS ENVIRONMENT;
DROP TABLE IF EXISTS PROPERTIES;
DROP SEQUENCE IF EXISTS PROPERTIES_ID_SEQ;
DROP SEQUENCE IF EXISTS ENVIRONMENT_ID_SEQ;
DROP SCHEMA IF EXISTS CONFIG;

CREATE SCHEMA CONFIG;
SET SCHEMA CONFIG;

CREATE SEQUENCE ENVIRONMENT_ID_SEQ START WITH 0 INCREMENT BY 50;
CREATE SEQUENCE PROPERTIES_ID_SEQ START WITH 0 INCREMENT BY 50;

CREATE TABLE ENVIRONMENT (
  ENVIRONMENT_ID BIGINT DEFAULT ENVIRONMENT_ID_SEQ.nextval NOT NULL,
  CREATED_BY_USER VARCHAR(255) NOT NULL,
  CREATION_TIME TIMESTAMP NOT NULL,
  LAST_MODIFICATION_TIME TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(255) NOT NULL,
  VERSION BIGINT NOT NULL,
  DESCRIPTION VARCHAR(255),
  NAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ENVIRONMENT_ID)
);


CREATE TABLE PROPERTIES (
  PROPERTIES_ID BIGINT DEFAULT PROPERTIES_ID_SEQ.nextval NOT NULL,
  CREATED_BY_USER VARCHAR(255) NOT NULL,
  CREATION_TIME TIMESTAMP NOT NULL,
  LAST_MODIFICATION_TIME TIMESTAMP NOT NULL,
  LAST_MODIFIED_BY_USER VARCHAR(255) NOT NULL,
  VERSION BIGINT NOT NULL,
  PROPERTY_KEY VARCHAR(512) NOT NULL ,
  PROPERTY_VALUE CLOB NOT NULL,
  PROPERTY_TYPE VARCHAR2(512) NOT NULL,
  ENVIRONEMNT_ID BIGINT NOT NULL REFERENCES ENVIRONMENT(ENVIRONMENT_ID),
  PRIMARY KEY (PROPERTIES_ID)
);




